// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6V1_hlAq7v60ugu69ZVWguatZbPLLu04',
    appId: '1:459947576024:web:43f34538461f8aaaa865ad',
    messagingSenderId: '459947576024',
    projectId: 'ai-interview-practice-ap-e57e4',
    authDomain: 'ai-interview-practice-ap-e57e4.firebaseapp.com',
    storageBucket: 'ai-interview-practice-ap-e57e4.firebasestorage.app',
    measurementId: 'G-5E4WE6996G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj9gsf3vwKB78ZTMj58YaE_mCLPOyFbII',
    appId: '1:459947576024:android:a21d53f6a8a3e7d7a865ad',
    messagingSenderId: '459947576024',
    projectId: 'ai-interview-practice-ap-e57e4',
    storageBucket: 'ai-interview-practice-ap-e57e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCopAjw9VsYi-XWnULRT5iMrrECoUept0w',
    appId: '1:459947576024:ios:ec258ffb765671afa865ad',
    messagingSenderId: '459947576024',
    projectId: 'ai-interview-practice-ap-e57e4',
    storageBucket: 'ai-interview-practice-ap-e57e4.firebasestorage.app',
    iosBundleId: 'com.example.aiInterviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCopAjw9VsYi-XWnULRT5iMrrECoUept0w',
    appId: '1:459947576024:ios:ec258ffb765671afa865ad',
    messagingSenderId: '459947576024',
    projectId: 'ai-interview-practice-ap-e57e4',
    storageBucket: 'ai-interview-practice-ap-e57e4.firebasestorage.app',
    iosBundleId: 'com.example.aiInterviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6V1_hlAq7v60ugu69ZVWguatZbPLLu04',
    appId: '1:459947576024:web:8fed6eaf1f69f779a865ad',
    messagingSenderId: '459947576024',
    projectId: 'ai-interview-practice-ap-e57e4',
    authDomain: 'ai-interview-practice-ap-e57e4.firebaseapp.com',
    storageBucket: 'ai-interview-practice-ap-e57e4.firebasestorage.app',
    measurementId: 'G-YW1V6VQPZP',
  );
}
